### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by doubles078** [doubles078/middle-earth#1]
## Overview
Figure out and implement a lightweight user management system.  User's should be able to create their own accounts, manage their information, and delete their profile.

## Tasks
- [ ] Research best practices for maintaining authentication/authorization with a NextJS application
- [ ] UX/UI for basic login buttons and modal
- [ ] Implement provider to maintain authorization state

## Nice to Haves
- [ ] Add social auth for Google and Facebook
