### ISSUE TITLE
Notification system

### ISSUE THREAD

**Issue by doubles078** [doubles078/middle-earth#12]
## Overview
Emails are the core of the user notification experience.  They should be quick, customized and informative based on their training plan.  

## Thoughts
Love the experience of 'The Morning Brew'

## Tasks
- [ ] Research the best option for sending lots of emails
- [ ] Find fun and clean email designs
- [ ] Design and implement first version of the email

## Nice to haves
- [ ] Weekly vs daily update toggling
- Special alerts: anything over an hour is a test day for calorie and hydration inputs while running
- Shoe alert - change shoes every 450 to 550 miles

## Designs
![baseeamil](https://user-images.githubusercontent.com/22918087/137598905-f4b7232a-0da1-4174-975b-d6ebabed282f.PNG)
