### ISSUE TITLE
Add a race form 

### ISSUE THREAD

**Issue by doubles078** [doubles078/middle-earth#6]
## Overview
Do some research on best practices with form UX.  User's should be able to sign up for a race with minimal distraction (i.e. too much superfluous information) while also feeling like they are receiving a custom training plan.

## Tasks
- [ ] Research best practices for UX
- [ ] Create a new Balsamiq flow for the ideal minimal information to generate the best topic
- [ ] Implement design for user signing up with state management

## Thoughts
- Only 1 race at a time
- Date
- Distance

## Nice to haves
- Routes (bike packing page)
- User writeups and notes
- Other stuff
- Sign ups instead of making customs

## Designs
![addrace](https://user-images.githubusercontent.com/22918087/137598013-1c5c1c46-673c-4cb4-b35b-c05ca789bd69.PNG)
