### ISSUE TITLE
Race information section

### ISSUE THREAD

**Issue by doubles078** [doubles078/middle-earth#7]
## Overview
A section of the dashboard that shows a user the statistics for their upcoming race.

## Tasks
- [ ] Create a 'Race' type
- [ ] Implement card design with information
- [ ] Implement 'edit' ability
- [ ] Create utility functions for 'per mile' pace calculations

## Designs
![raceinfo](https://user-images.githubusercontent.com/22918087/137598225-22dc9d27-0429-46f9-a80c-1625b6e1c41d.PNG)
