### ISSUE TITLE
Day section of dashboard

### ISSUE THREAD

**Issue by doubles078** [doubles078/middle-earth#8]
## Overview
The section of the dashboard page explaining statistics or 'to dos' for the current day.

## Tasks
- [ ] Create the "Todays run" card including 'check in' ability and target pace calculations
- [ ] Create the 'hydration' card including water intake calculations
- [ ] Create calorie count card including calorie counting calculations
- [ ] Create the target heart zone card, along with target heart zones

## Designs
![day](https://user-images.githubusercontent.com/22918087/137598328-c7470b86-92e3-4464-9be6-1b173310f531.PNG)
