### ISSUE TITLE
Race calendar

### ISSUE THREAD

**Issue by doubles078** [doubles078/middle-earth#9]
## Overview
A small calendar in the dashboard allowing a user to look ahead in their schedule and quickly see what runs they are doing on which days.  Users should be able to select days and have the right side of the dashboard update, as well as 'edit my race' to update future days they know need to be changed.

## Tasks 
- [ ] Research an easy to use calendar component
- [ ] Balsamiq design a full page calendar view (for viewing and editing)
- [ ]  Create a 'day card' along with edit day functionality (alt version of the left side day card?)

## Nice to haves
- Week summary cool line chart

## Designs
![racecalendar](https://user-images.githubusercontent.com/22918087/137598584-61291398-92cf-4555-ba22-088787cf4c6f.PNG)
